server:
  port: 9090

spring:
  profiles:
    active:
      - jfranke
      - vanechoic
      - Nils
      - dev
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    repositories:
      enabled: true
    show-sql: true